### PR TITLE
Add optional attributes and better errors

### PR DESCRIPTION
**Pull request by emhoracek**

### CODE REVIEW

**Comment by dbp** [comment]
This looks great! Esp. the error messages.

**Comment by emhoracek** [comment]
I had to use `force` from deepseq to test the errors, that was interesting

**Comment by dbp** [comment]
Yeah, that's really neat :) 

All of this is making me so curious about benchmarking. I've essentially never done it (as haskell has pretty much always been fast enough :P), but I'm wondering if there are places where forcing stuff could speed stuff up. But I don't actually know how to write the tests (ie, benchmarks) to prove anything!

**Comment by emhoracek** [comment]
one or both of us should've put Haskell benchmarking under "puzzling"

:question: :question: :question:

**Comment by dbp** [comment]
So true...

**Pull request merged**
